name: useless_trivia
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: 2.8.0
  firebase_analytics: 10.1.6
  firebase_crashlytics: 3.0.17
  firebase_messaging: 14.3.0
  firebase_remote_config: 3.0.15

  # Database & requests
  drift: ^2.5.0
  chopper: 6.1.1
  json_annotation: ^4.1.0
  path_provider: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0

  # UI
  flutter_svg: 2.0.4 # lower version include in flutter_html
  font_awesome_flutter: 10.4.0
  country_icons: 2.0.2
  flutter_map: 3.1.0
  flutter_map_marker_cluster: 1.1.0
  material_design_icons_flutter: 6.0.7096
  bubble: 1.2.1 # 2 years old, Dart 3 compatible.
  google_maps_flutter: 2.2.5
  webview_flutter: 4.0.7 # lower version include in flutter_html
  cached_network_image: 3.2.3
  another_flushbar: 1.12.29 # flushbar: ^1.10.4 # could not find a more recent version, this is basically the same library with null safety.
  auto_route: 6.0.1
  pref: 2.7.1 # preferences: ^5.2.0 package is discontinued, replaced by pref.
  theme_provider: 0.5.0 # 2 years old, but has null-safety.
  faker: 2.1.0

  # Dependency injection
  injectable: 2.1.0
#  get_it: ^4.0.4  # not needed because of other dependencies. This dependency uses 7.2.0.

  # Native functionality
  shared_preferences: 2.0.20
  url_launcher: 6.1.10
  flutter_local_notifications: 13.0.0 # lower version include in flutter_html
  maps_launcher: 2.2.0
  package_info_plus: 3.0.3 # package_info 2.0.2 is 22 months old and deprecated. Replaced by package_info_plus.

  # Data manipulation
  intl: 0.18.0
  latlong2: 0.8.1 #  latlong: ^0.6.1 is very old, depends on logging
  fluster: 1.2.0 # 23 month old, Dart 3 compatible.

#   Quality control
#  flutter_stetho: ^0.5.2 # The plugin `flutter_stetho` uses a deprecated version of the Android embedding.

  # Domain Driven Design
  rxdart: 0.27.7
  dartz: 0.10.1
  kt_dart: 1.1.0
  meta: 1.8.0
  flutter_bloc: 8.1.2
  freezed_annotation: 2.2.0
  flutter_hooks: 0.18.6

  # Just included for this project.
  path:
  uuid: 3.0.7
  built_value: ^8.0.0
  hive_generator: ^2.0.0
  flutter_html: 3.0.0-alpha.6
#  flutter_widget_from_html: 0.10.0
  flutter_osm_plugin: ^0.51.0
  freezed: 2.3.2
  automatic_animated_list: 1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: 2.0.1
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: '>=4.4.0'
  drift_dev: ^2.5.2
  injectable_generator: 2.1.4
  chopper_generator: 6.0.0
  auto_route_generator: 6.0.0
  flutter_lints: ^2.0.0
  import_sorter: 4.6.0
  flutter_launcher_icons: 0.12.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
